version: '3'
services:
  keycloak:
    image: jboss/keycloak
    ports:
      - 8081:8080
    container_name: keycloak
    networks:
      - camunda
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
  camunda:
    image: process_registration
    ports:
      - 8080:8080
    container_name: camunda
    networks:
      - camunda
    links:
      - keycloak:keycloak
    depends_on:
      - keycloak
networks:
  camunda:
    driver: bridge